# Generated by Django 4.2.4 on 2023-08-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin_order_product_shipment_shipmentdetail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('house_no', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('sub_district', models.CharField(max_length=50)),
                ('provine', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=11)),
            ],
        ),
    ]
