# Generated by Django 4.2.4 on 2023-08-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CA', 'cart'), ('OR', 'order'), ('SH', 'shipment')], default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('SU', 'success'), ('SH', 'shipping'), ('SU', 'success')], default='PE', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.FloatField(default=0),
        ),
    ]
