# Generated by Django 4.2.4 on 2023-08-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_status_shipment_status_user_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(to='api.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ManyToManyField(to='api.user'),
        ),
    ]
