# Generated by Django 4.2.4 on 2023-08-23 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shipment'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='address',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
