# Generated by Django 4.2.4 on 2023-08-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='address',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
