# Generated by Django 4.2.4 on 2023-08-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipment',
            new_name='shipment_id',
        ),
    ]
