# Generated by Django 4.2.4 on 2023-08-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_shipment_recieved_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='recieved_date',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_date',
        ),
    ]
