# Generated by Django 4.2.4 on 2023-08-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_shipment_recieved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='recieved_date',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_date',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
