# Generated by Django 4.2.4 on 2023-08-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_shipment_recieved_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_date',
        ),
    ]
