# Generated by Django 4.2.4 on 2023-08-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_shipment_shipment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='updated_at',
        ),
    ]
